### ISSUE TITLE
Why is message signing not required anymore?

### ISSUE THREAD

**Issue by bangbaew** [PaymentsNZ/API-Payments-Initiation#37]
To the best of my understanding, PaymentsNZ obtained some necessary resources from Open Banking UK. According to Open Banking UK's OpenAPI specifications, payload signing in the form of a detached JSON Web Signature (JWS) in the `x-jws-signature` header is required. However, based on PaymentsNZ documentation, it appears that this requirement is no longer mandatory. I am curious about the rationale behind this change. Is there no longer a need to consider message integrity? I appreciate any insights you can provide on this matter.

![image](https://github.com/PaymentsNZ/API-Payments-Initiation/assets/29559559/967fdf20-452b-4cfd-8a38-b322c50cbd75)

**Comment by NigelSomerfieldPNZ** [comment]
Please address any questions or comments to our feedback form here: https://paymentsnz.atlassian.net/servicedesk/customer/portal/1
